import os, sys
# Add the project folder to path
PACKAGE_PARENT = '..'
SCRIPT_DIR = os.path.dirname(os.path.realpath(os.path.join(os.getcwd(), os.path.expanduser(__file__))))
sys.path.append(os.path.normpath(os.path.join(SCRIPT_DIR, PACKAGE_PARENT)))

from DeepLearning.model import Model
from DeepLearning.model import denormalize_image
import numpy as np
import cv2
import matplotlib.pyplot as plt


# Draws cars, learning material in datafolder+paths
paths = ['Car/']
data_folder = "/media/cf2017/levy/tensorflow/parking_place2/"

# DCGAN=True
mod = Model(paths, data_folder=data_folder,
            epochs=1, img_size=64, model_name='gen_model',
            learning_rate=0.0002, DCGAN=True)

# Trains model, mnist dataset built in to do sanity tests
mod.DCGAN(mnist_data=False)
# Model can be loaded with: (only works with models generated by this project)
# mod = Model.load_model(data_folder + 'models/gen_model2')

# Use random noise to generate images
z = np.random.uniform(0., 1., size=[4, mod.z_dim])
images = mod.predict_DCGAN(z)
# Generated images are normalized, so denormalize them
images = denormalize_image(images)
# Show them in a grid
new_im = np.vstack(([(np.hstack(([images[i * j] for i in range(1)]))) for j in range(1)]))
cv2.imshow('main', new_im)
cv2.waitKey()

# Another way to show images
f, a = plt.subplots(4, 10, figsize=(10, 4))
for i in range(10):
    # Noise input.
    z = np.random.uniform(0., 1., size=[4, mod.z_dim])
    images = np.array(mod.predict_DCGAN(z))
    images = denormalize_image(images)
    for j in range(4):
        # Generate image from noise. Extend to 3 channels for matplot figure.
        img = np.reshape(np.repeat(images[j][:, :, np.newaxis], 3, axis=2),
                         newshape=(mod.img_size, mod.img_size, 3))
        a[j][i].imshow(img)
f.show()
plt.draw()
plt.waitforbuttonpress()

